# Use the official Dev Container base image
FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

# Install p2pfl with pip and cache it in the image
RUN pip install --no-cache-dir p2pfl[torch]
